palavra = str(input('Digite uma palavra: '))
print(f'O tipo primitivo dessa palavra é {type(palavra)}')
print(f'Só tem espaços: {palavra.isspace()}')
print(f'É um númerod: {palavra.isnumeric()}')
print(f'É alfabético: {palavra.isalpha()}')
print(f'É alfanumérico: {palavra.isalnum()}')
print(f'Está em maiúsculo: {palavra.isupper()}')
print(f'Está em minúsculo: {palavra.islower()}')
print(f'Está capitalizada: {palavra.istitle()}')